# 🔥💎⚡ LEGENDARY PI DEVELOPMENT DEPLOYMENT SCRIPT ⚡💎🔥
# Auto-generated by Pi-Laptop Fusion System

Write-Host "🔥💎⚡ LEGENDARY PI DEVELOPMENT DEPLOYMENT ⚡💎🔥" -ForegroundColor Magenta
Write-Host "================================================================" -ForegroundColor Cyan
Write-Host "🎯 MISSION: Transform Pi into development powerhouse!" -ForegroundColor Green
Write-Host "📱 SD Card: 'ras pi card' (E:) - 128GB READY!" -ForegroundColor Yellow
Write-Host "🌐 Network: Gigabit Ethernet Bridge Deployment" -ForegroundColor Blue
Write-Host "================================================================" -ForegroundColor Cyan

Write-Host ""
Write-Host "🚀 PHASE 1: DEPLOYING EXISTING BRIDGE SYSTEM..." -ForegroundColor Magenta
Write-Host "================================================" -ForegroundColor DarkMagenta

# Check if existing deployment script exists
if (Test-Path ".\🎊🚀💎⚡_LEGENDARY_HYBRID_PI_EMPIRE_DEPLOYMENT_⚡💎🚀🎊.ps1") {
    Write-Host "✅ Found existing empire deployment system!" -ForegroundColor Green
    Write-Host "🎊 Executing legendary Pi empire deployment..." -ForegroundColor Cyan
    
    # Execute the existing deployment with development optimizations
    .\🎊🚀💎⚡_LEGENDARY_HYBRID_PI_EMPIRE_DEPLOYMENT_⚡💎🚀🎊.ps1 -Mode deploy -Monitor
    
    if ($LASTEXITCODE -eq 0) {
        Write-Host "🎊 Empire deployment successful!" -ForegroundColor Green
        $PiIP = "192.168.137.2"  # Default discovered Pi IP
    } else {
        Write-Host "⚠️ Empire deployment had issues, checking alternatives..." -ForegroundColor Yellow
        $PiIP = Read-Host "Enter Pi IP address manually (or press Enter for 192.168.137.2)"
        if (-not $PiIP) { $PiIP = "192.168.137.2" }
    }
} else {
    Write-Host "📁 Empire deployment script not found, using direct approach..." -ForegroundColor Yellow
    $PiIP = Read-Host "Enter Pi IP address (default: 192.168.137.2)"
    if (-not $PiIP) { $PiIP = "192.168.137.2" }
}

Write-Host ""
Write-Host "🧠 PHASE 2: INSTALLING DEVELOPMENT IDES..." -ForegroundColor Magenta
Write-Host "===========================================" -ForegroundColor DarkMagenta
Write-Host "🎯 Target Pi: $PiIP" -ForegroundColor Green

# Development IDE installation script
$DevSetupScript = @'
#!/bin/bash
echo "🧠💎⚡ PI DEVELOPMENT IDE INSTALLATION ⚡💎🧠"
echo "================================================"

# Update system
echo "📦 Updating system packages..."
sudo apt-get update -y

# Install development IDEs
echo "🥷 Installing Ninja-IDE..."
sudo apt-get install -y ninja-ide

echo "⚡ Installing Geany..."
sudo apt-get install -y geany

echo "📝 Installing additional development tools..."
sudo apt-get install -y vim git curl wget htop tree

# Install Python development tools
echo "🐍 Setting up Python development environment..."
sudo apt-get install -y python3-pip python3-venv python3-dev
pip3 install --upgrade pip setuptools wheel
pip3 install jupyter notebook ipython pandas numpy matplotlib

# Install VS Code Server for remote development
echo "💻 Installing VS Code Server..."
curl -fsSL https://code-server.dev/install.sh | sh
sudo systemctl enable code-server@$(whoami)

# Configure VS Code Server
mkdir -p ~/.config/code-server
cat > ~/.config/code-server/config.yaml << EOF
bind-addr: 0.0.0.0:8080
auth: password
password: legendary
cert: false
EOF

# Start services
echo "🚀 Starting development services..."
sudo systemctl start code-server@$(whoami)

# Display access information
LOCAL_IP=$(hostname -I | awk '{print $1}')
echo ""
echo "🎊 DEVELOPMENT ENVIRONMENT READY!"
echo "================================="
echo "🥷 Ninja-IDE: SSH with X11 forwarding"
echo "⚡ Geany: SSH with X11 forwarding"
echo "💻 VS Code Server: http://$LOCAL_IP:8080 (password: legendary)"
echo "📓 Jupyter: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser"
echo "🌐 SSH Access: ssh $(whoami)@$LOCAL_IP"

echo ""
echo "🔧 DEVELOPMENT SETUP COMPLETE!"
'@

Write-Host "📡 Connecting to Pi and installing development environment..." -ForegroundColor Cyan

try {
    # Test Pi connectivity
    $PingResult = Test-Connection -ComputerName $PiIP -Count 2 -Quiet
    if (-not $PingResult) {
        Write-Host "❌ Cannot reach Pi at $PiIP" -ForegroundColor Red
        Write-Host "🔍 Please check network connection and Pi status" -ForegroundColor Yellow
        exit 1
    }
    
    Write-Host "✅ Pi reachable at $PiIP" -ForegroundColor Green
    Write-Host "🚀 Deploying development environment..." -ForegroundColor Cyan
    
    # Deploy development setup
    $DevSetupScript | ssh "broski@$PiIP" "bash -s"
    
    if ($LASTEXITCODE -eq 0) {
        Write-Host ""
        Write-Host "🎊 DEVELOPMENT DEPLOYMENT SUCCESS!" -ForegroundColor Green
        Write-Host "===================================" -ForegroundColor DarkGreen
    } else {
        Write-Host "⚠️ Some development tools may need manual installation" -ForegroundColor Yellow
    }
    
} catch {
    Write-Host "❌ SSH connection failed: $($_.Exception.Message)" -ForegroundColor Red
    Write-Host "💡 Manual setup instructions:" -ForegroundColor Cyan
    Write-Host "   1. SSH to Pi: ssh broski@$PiIP" -ForegroundColor White
    Write-Host "   2. Run the development setup script manually" -ForegroundColor White
}

Write-Host ""
Write-Host "🔗 PHASE 3: CONFIGURING REMOTE ACCESS..." -ForegroundColor Magenta
Write-Host "=========================================" -ForegroundColor DarkMagenta

Write-Host "🌐 Remote Development Access Points:" -ForegroundColor Cyan
Write-Host "   🥷 Ninja-IDE: ssh -X broski@$PiIP" -ForegroundColor White
Write-Host "      Then run: ninja-ide" -ForegroundColor Gray
Write-Host ""
Write-Host "   ⚡ Geany: ssh -X broski@$PiIP" -ForegroundColor White  
Write-Host "      Then run: geany" -ForegroundColor Gray
Write-Host ""
Write-Host "   💻 VS Code Server: http://$PiIP`:8080" -ForegroundColor White
Write-Host "      Password: legendary" -ForegroundColor Gray
Write-Host ""
Write-Host "   📓 Jupyter Notebook: ssh broski@$PiIP" -ForegroundColor White
Write-Host "      Then run: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser" -ForegroundColor Gray
Write-Host "      Access: http://$PiIP`:8888" -ForegroundColor Gray

Write-Host ""
Write-Host "📋 PHASE 4: DEVELOPMENT WORKFLOW SETUP..." -ForegroundColor Magenta
Write-Host "==========================================" -ForegroundColor DarkMagenta

Write-Host "🔄 Code Synchronization Options:" -ForegroundColor Cyan
Write-Host "   📁 SSHFS: Mount Pi filesystem on laptop" -ForegroundColor White
Write-Host "      sshfs broski@$PiIP`:/home/broski ~/pi-mount" -ForegroundColor Gray
Write-Host ""
Write-Host "   🔄 Rsync: Sync project folders" -ForegroundColor White
Write-Host "      rsync -av ./project/ broski@$PiIP`:/home/broski/project/" -ForegroundColor Gray
Write-Host ""
Write-Host "   📦 Git: Version control across devices" -ForegroundColor White
Write-Host "      git clone, commit, push/pull for sync" -ForegroundColor Gray

Write-Host ""
Write-Host "🎊🎊🎊 LEGENDARY PI DEVELOPMENT POWERHOUSE READY! 🎊🎊🎊" -ForegroundColor Magenta
Write-Host "================================================================" -ForegroundColor Cyan
Write-Host "🚀 Your Pi is now a LEGENDARY development accelerator!" -ForegroundColor Green
Write-Host "💎 Multiple IDEs available for different development needs" -ForegroundColor Yellow
Write-Host "⚡ Gigabit speeds for instant file transfers and real-time sync" -ForegroundColor Blue
Write-Host "🌐 Remote access from laptop browser or SSH with GUI forwarding" -ForegroundColor Magenta
Write-Host ""
Write-Host "🎯 NEXT STEPS:" -ForegroundColor Cyan
Write-Host "   1. Test remote IDE access" -ForegroundColor White
Write-Host "   2. Setup your development projects" -ForegroundColor White  
Write-Host "   3. Configure code synchronization" -ForegroundColor White
Write-Host "   4. Experience LEGENDARY hybrid development!" -ForegroundColor White
Write-Host ""
Write-Host "🔥💎⚡ PI-LAPTOP FUSION DEPLOYMENT COMPLETE! ⚡💎🔥" -ForegroundColor Magenta
